name: Deploy to Cloud Run

on:
  push:
    branches:
      - docker # O la rama que uses para tus despliegues (ej. master, develop)

env:
  PROJECT_ID: noxistence-site-v1 # Reemplaza con tu ID de proyecto de GCP
  SERVICE_NAME: noxistence-site # Reemplaza con el nombre de tu servicio de Cloud Run
  REGION: us-central1 # Reemplaza con la región de tu servicio de Cloud Run (ej. us-central1, europe-west1)
  GAR_LOCATION: us-central1 #new

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: 'write' # Añadido para permitir la publicación en GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Autenticación con Google Cloud (necesaria para el comando de despliegue)
      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      
      # Inicia sesión en GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Convert repository name to lowercase for Docker tag
      - name: Set repository name to lowercase
        id: string
        run: echo "repository_lowercase=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # Construye y publica la imagen en GHCR
      - name: Build and push Docker image to GHCR
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.string.outputs.repository_lowercase }}:${{ github.sha }}
          labels: |
            "run.googleapis.com/location=${{ env.REGION }}"
            "run.googleapis.com/service=${{ env.SERVICE_NAME }}"

      # Despliega en Cloud Run usando la imagen de GHCR
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ghcr.io/${{ steps.string.outputs.repository_lowercase }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated